sudo: false
language: go
go:
# math/rand.Shuffle didn't exist in 1.9
#  - "1.9"
  - "1.10"
  - "1.11"
  - tip
env:
  - GOOS=linux GOARCH=amd64
  - GOOS=windows GOARCH=amd64
  - GOOS=darwin GOARCH=amd64
# Should add test builds on other platforms to check fallback plan
#  - GOOS=linux GOARCH=arm
#  - GOOS=linux GOARCH=mips
